# Generated by Django 2.2.24 on 2022-02-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220218_1152'),
    ]

    operations = [
    ]
