# Generated by Django 2.2.24 on 2022-02-20 16:31
import phonenumbers
from django.db import migrations


def normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(number):
            normalize_number = f'+{number.country_code}{number.national_number}'
            flat.owner_pure_phone = normalize_number
        else:
            flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220219_2038'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumber),
    ]
