# Generated by Django 2.2.24 on 2022-02-21 13:45

from django.db import migrations


def set_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )
        owner.flats_ownership.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220221_1610'),
    ]

    operations = [
        migrations.RunPython(set_owners),
    ]
